version: "3.3"
services:
  mock:
    build: ./mock
    ports: 
      - 9090:9090
  redis:
    image: redis:latest
    ports: 
      - "9999:6379"
  rabbitmq:
    image: rabbitmq:latest
    ports:
      - "15672:15672"
      - "5672:5672"